In [1]:
import torch

c:\Users\Carlos\anaconda3\envs\pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
def binary_distance(X, Y):
    """Compute distance matrix between  rows of X, Y.

    d(x_i, y_j) = 1 if x_i == y_j, 0 in other case.

    for all rows x_i in X, y_j in Y

    """
    return (X.unsqueeze(1) == Y.unsqueeze(0)).all(-1).float()

In [9]:
def compute_centroids(X, y):
    label_matrix = binary_distance(y.unique().unsqueeze(1), y.unsqueeze(1))
    label_matrix = torch.div(label_matrix, torch.sum(label_matrix, dim=1).unsqueeze(1))
    return torch.matmul(label_matrix, X), y.unique()

In [10]:
prueba = torch.tensor([2,3,2,2,1,2,3,4], dtype=torch.float)

In [11]:
etiquetas = prueba.unique()

In [5]:
matriz = binary_distance(etiquetas.unsqueeze(1), prueba.unsqueeze(1))

In [6]:
matriz

tensor([[0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 1., 1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
X = torch.rand((5,6), dtype=torch.float)
y = torch.tensor([2,3,2,2,1], dtype=torch.float)

In [13]:
X

tensor([[0.8297, 0.3224, 0.5171, 0.4091, 0.2864, 0.7082],
        [0.8326, 0.8648, 0.8250, 0.7273, 0.6693, 0.8729],
        [0.8528, 0.2973, 0.4668, 0.0865, 0.9033, 0.1066],
        [0.0826, 0.5666, 0.1821, 0.4346, 0.9174, 0.1333],
        [0.2146, 0.4583, 0.8526, 0.2099, 0.6207, 0.7287]])

In [14]:
compute_centroids(X,y)

(tensor([[0.2146, 0.4583, 0.8526, 0.2099, 0.6207, 0.7287],
         [0.5884, 0.3954, 0.3887, 0.3101, 0.7024, 0.3160],
         [0.8326, 0.8648, 0.8250, 0.7273, 0.6693, 0.8729]]),
 tensor([1., 2., 3.]))